# .github/workflows/run-tests.yml
name: "Conditional Test Suite"

on:
  push:
    # (Optional) specify branches if needed, e.g., main:
    # branches: [ main ]

jobs:
  run-tests:
    # Only run this job if commit message contains one of the trigger phrases
    if: >-
      contains(github.event.head_commit.message, '[run-tests]')
    #   contains(github.event.head_commit.message, 'run tests, on error exit') ||
    #   contains(github.event.head_commit.message, 'run tests, on error continue')
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # (Optional) Set up any dependencies (e.g. install docker-compose if needed)
      - name: Ensure Docker Compose V2
        run: |
          echo "Ensuring Docker Compose V2 (docker compose) is available"
          if ! docker compose version &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin
          fi

      # Configure error-handling mode based on commit message
      - name: Configure error mode = exit on first error
        # if: contains(github.event.head_commit.message, 'run tests, on error exit')
        run: echo "MODE=exit" >> $GITHUB_ENV

      # - name: Configure error mode = continue on errors
      #   if: contains(github.event.head_commit.message, 'run tests, on error continue')
      #   run: echo "MODE=continue" >> $GITHUB_ENV

      # Run all tests in the tests directory, each in its own subdirectory
      - name: Run all tests in subdirectories
        run: |
          set -e

          workdir=$(pwd)
          echo "Current working directory: $workdir"

          if [ -f "./requirements.txt" ]; then
            python3 -m venv "./migrator_venv"
            source "./migrator_venv/bin/activate"
            pip install --upgrade pip
            pip install -r "./requirements.txt"
          fi

          cd "$workdir/tests"
          echo "Current working directory: $(pwd)"
            for dir in $workdir/tests/*/; do
            if [ -f "$dir/run_full_test.sh" ]; then
              echo "Running tests in $dir"
              cd $workdir/test/$dir
              bash "./run_full_test.sh"
              if [ "$MODE" = "exit" ] && [ $? -ne 0 ]; then
                echo "Test failed in $dir, exiting."
                exit 1
              fi
              echo "Test completed in $dir"
              cd $workdir/tests
            else
              echo "No run_full_test.sh in $dir, skipping."
            fi
          done
